<?xml version="1.0"?>
<robot name="beam_setup" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name = "table_height" value = "0.05" />
<xacro:property name="pi" value="3.1415" />

<material name = "black">
    <color rgba = "0 0 0 1"/>
</material>

<material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>

<xacro:macro name = "default_inertial" params = "mass">
    <inertial>
        <mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
</xacro:macro>


<!-- world -->
<link name = "world"/>
<!-- table -->
<link name = "table_link">
    <visual>
        <geometry>
            <box size="1.3 0.8 ${table_height}"/>
        </geometry>
        <material name = "grey"/>
    </visual>
    <collision>
        <geometry>
            <box size="1.3 0.8 ${table_height}"/>
        </geometry>
    </collision>
    <xacro:default_inertial mass="15"/>
</link>

<joint name = "world_to_table" type = "fixed">
    <parent link = "world" />
    <child link = "table_link" />
    <origin xyz = "0 0 1.5" />
</joint>

<!-- panda -->
<xacro:include filename="$(find franka_description)/robots/panda_arm_with_dyn_params.xacro" />
<xacro:panda_arm connected_to="table_link" xyz = "-0.4 0 ${table_height/2}" rpy="0 0 0"/>

<!-- beam approximated as a pendulum -->
<link name = "pendulum_rod">
    <visual>
        <origin xyz="0.26 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
            <cylinder length="0.52" radius="0.005"/>
        </geometry>
    </visual>
    <collision>
        <geometry>
            <cylinder length="0.52" radius="0.05"/>
        </geometry>
    </collision>
    <inertial>
        <mass value="0.0" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
    </inertial>
</link>

<joint name = "panda_to_pendulum" type = "revolute">
    <parent link = "panda_link8"/>
    <child link = "pendulum_rod"/>
    <axis xyz="0 0 1"/>
    <origin rpy = "${-pi/2} 0 ${-3*pi/4}" />
    <limit effort="100.0" lower="-${pi}" upper="${pi}" velocity="1.5"/>
</joint>

<link name = "pendulum_mass">
    <visual>
        <origin xyz="0 0 0" rpy="0 ${pi/2} 0" />
        <geometry>
            <sphere radius="0.025" />
        </geometry>
    </visual>
    <collision>
        <geometry>
            <sphere radius="0.025" />
        </geometry>
    </collision>
    <inertial>
        <mass value="2.33" />
        <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
    </inertial>
</link>

<joint name = "panda_rod_to_mass" type = "fixed">
    <parent link = "pendulum_rod"/>
    <child link = "pendulum_mass"/>
    <axis xyz="0 0 1"/>
    <origin rpy = "0 0 0" xyz="0.52 0 0"/>
    <limit effort="100.0" lower="-${pi}" upper="${pi}" velocity="1.5"/>
</joint>


</robot>