<?xml version="1.0"?>
<robot name="beam_setup" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name = "table_height" value = "0.05" />
<xacro:property name="pi" value="3.1415" />

<material name = "black">
    <color rgba = "0 0 0 1"/>
</material>

<material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>

<xacro:macro name = "default_inertial" params = "mass">
    <inertial>
        <mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
    </inertial>
</xacro:macro>


<!-- world -->
<link name = "world"/>

<!-- table -->
<link name = "table_link">
    <visual>
        <geometry>
            <box size="1.3 0.8 ${table_height}"/>
        </geometry>
        <material name = "grey"/>
    </visual>
    <collision>
        <geometry>
            <box size="1.3 0.8 ${table_height}"/>
        </geometry>
    </collision>
    <xacro:default_inertial mass="15"/>
</link>

<joint name = "world_to_table" type = "fixed">
    <parent link = "world" />
    <child link = "table_link" />
    <origin xyz = "0 0 1.5" />
</joint>

<!-- panda -->
<xacro:include filename="$(find franka_description)/robots/panda_arm.xacro" />
<xacro:panda_arm connected_to="table_link" xyz = "-0.4 0 ${table_height/2}" rpy="0 0 0"/>

<!-- beam -->
<link name = "beam">
    <visual>
        <origin xyz="-0.25 -0.015 0" rpy="0 0 0" />
        <geometry>
            <box size = "0.6 0.08 0.005" />
        </geometry>
    </visual>
    <collision>
        <geometry>
            <box size = "0.2 0.05 0.005" />
        </geometry>
    </collision>
    <xacro:default_inertial mass="0.5"/>
</link>

<joint name = "panda_to_beam" type = "fixed">
    <parent link = "panda_link8"/>
    <child link = "beam"/>
    <origin rpy = "0 0 ${pi/4}" />
</joint>

</robot>